### ISSUE TITLE
BTL is not working

### ISSUE THREAD

**Issue by madhead** [knipknap/better-tool-library#8]
### Steps to reproduce

1. Install BTL via the addon manager.
2. Restart FreeCAD.
3. Try to find / use BTL.

### Expected behavior

A BTL icon appears somewhere in the "Path" workbench. Clicking it opens the BTL GUI.

### Actual behavior

Not BTL icon appears in the UI:

![image](https://github.com/knipknap/better-tool-library/assets/577360/46042dc8-9408-48e5-ac42-1799168860ab)

There is an error in the report view:

```
02:53:54  During initialization the error "numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject" occurred in /home/siarhei_krukau/snap/freecad/common/Mod/btl/./InitGui.py
02:53:54  Please look into the log file for further information
```

### FreeCAD info

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33991 (Git) Snap 754
Build type: Release
Branch: master
Hash: bb13c179e90895e320445ed3ce0a5389c3688151
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
Installed mods: 
  * btl 0.9.9
```

### The logs

```
﻿Msg: FreeCAD 0.22.0, Libs: 0.22.0devR33991 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Log: Time = 2023-Aug-29 03:08:39
Log: AboutImage = freecadabout
Log: AppDataSkipVendor = true
Log: AppHomePath = /snap/freecad/754/usr/
Log: AppIcon = freecad
Log: AppTempPath = /home/madhead/snap/freecad/common/temp/
Log: BOOST_VERSION = 1_74
Log: BinPath = /snap/freecad/754/usr/bin/
Log: BuildRepositoryURL = git://github.com/FreeCAD/FreeCAD.git master
Log: BuildRevision = 33991 (Git)
Log: BuildRevisionBranch = master
Log: BuildRevisionDate = 2023/08/26 19:03:58
Log: BuildRevisionHash = bb13c179e90895e320445ed3ce0a5389c3688151
Log: BuildVersionMajor = 0
Log: BuildVersionMinor = 22
Log: BuildVersionPoint = 0
Log: BuildVersionSuffix = dev
Log: Console = 0
Log: CopyrightInfo = © Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##


Log: Debug = 0
Log: DocPath = /snap/freecad/754/usr/doc/
Log: EIGEN_VERSION = 3.4.0
Log: ExeName = FreeCAD
Log: ExeVendor = FreeCAD
Log: ExeVersion = 0.22.0
Log: LoggingConsole = 1
Log: LoggingFile = 1
Log: LoggingFileName = /home/madhead/FC.log
Log: MaintainerUrl = http://www.freecad.org/wiki/Main_Page
Log: OCC_VERSION = 7.7.1
Log: PATH = /snap/freecad/754/usr/sbin:/snap/freecad/754/usr/bin:/snap/freecad/754/sbin:/snap/freecad/754/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/freecad/754/kf5/usr/bin
Log: PYSIDE_VERSION = 5.15.10
Log: PYTHONPATH = 
Log: PYTHON_VERSION = 3.10.12
Log: PythonSearchPath = /snap/freecad/754/usr/lib/python310.zip:/snap/freecad/754/usr/lib/python3.10:/snap/freecad/754/usr/lib/python3.10/lib-dynload
Log: QT_VERSION = 5.15.10
Log: RunMode = Gui
Log: SMESH_VERSION = 7.7.1.0
Log: SplashAlignment = Bottom|Left
Log: SplashInfoColor = #8aadf4
Log: SplashInfoPosition = 6,75
Log: SplashScreen = freecadsplash
Log: SplashTextColor = #8aadf4
Log: StartWorkbench = StartWorkbench
Log: SystemParameter = /home/madhead/snap/freecad/common/system.cfg
Log: UserAppData = /home/madhead/snap/freecad/common/
Log: UserCachePath = /home/madhead/snap/freecad/common/temp/
Log: UserConfigPath = /home/madhead/snap/freecad/common/
Log: UserHomePath = /home/madhead/snap/freecad/common
Log: UserMacroPath = /home/madhead/snap/freecad/common/
Log: UserParameter = /home/madhead/snap/freecad/common/user.cfg
Log: Verbose = 
Log: XERCESC_VERSION = 3.2.3
Log: Create Application
Log: Run App init script
Log: Init: starting App::FreeCADInit.py
Log: Init:   Searching for modules...
Log: Init:      Initializing /snap/freecad/754/usr/Mod/AddonManager... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Arch... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Draft... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Fem... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Idf... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Import... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Inspection... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Material... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Measure... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Mesh... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/MeshPart... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/OpenSCAD... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Part... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/PartDesign... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Path... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Plot(Init.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Points... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/ReverseEngineering... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Robot... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Show(Init.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Sketcher... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/SnapSetup... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Spreadsheet... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Start... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Surface... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/TechDraw... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Test... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Tux(Init.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Web... done
Log: Init:      Initializing /home/madhead/snap/freecad/common/Mod/btl/./(Init.py not found)... ignore
Log: Using /snap/freecad/754/usr/Mod as module path!
Log: System path after init:
Log:    /snap/freecad/754/usr/bin
Log:    /snap/freecad/754/usr/Mod/AddonManager
Log:    /snap/freecad/754/usr/Mod/Arch
Log:    /snap/freecad/754/usr/Mod/Draft
Log:    /snap/freecad/754/usr/Mod/Fem
Log:    /snap/freecad/754/usr/Mod/Idf
Log:    /snap/freecad/754/usr/Mod/Import
Log:    /snap/freecad/754/usr/Mod/Inspection
Log:    /snap/freecad/754/usr/Mod/Material
Log:    /snap/freecad/754/usr/Mod/Measure
Log:    /snap/freecad/754/usr/Mod/Mesh
Log:    /snap/freecad/754/usr/Mod/MeshPart
Log:    /snap/freecad/754/usr/Mod/OpenSCAD
Log:    /snap/freecad/754/usr/Mod/Part
Log:    /snap/freecad/754/usr/Mod/PartDesign
Log:    /snap/freecad/754/usr/Mod/Path
Log:    /snap/freecad/754/usr/Mod/Plot
Log:    /snap/freecad/754/usr/Mod/Points
Log:    /snap/freecad/754/usr/Mod/ReverseEngineering
Log:    /snap/freecad/754/usr/Mod/Robot
Log:    /snap/freecad/754/usr/Mod/Show
Log:    /snap/freecad/754/usr/Mod/Sketcher
Log:    /snap/freecad/754/usr/Mod/SnapSetup
Log:    /snap/freecad/754/usr/Mod/Spreadsheet
Log:    /snap/freecad/754/usr/Mod/Start
Log:    /snap/freecad/754/usr/Mod/Surface
Log:    /snap/freecad/754/usr/Mod/TechDraw
Log:    /snap/freecad/754/usr/Mod/Test
Log:    /snap/freecad/754/usr/Mod/Tux
Log:    /snap/freecad/754/usr/Mod/Web
Log:    /home/madhead/snap/freecad/common/Mod/btl
Log:    /home/madhead/snap/freecad/common/Mod/btl/./
Log:    /snap/freecad/754/usr/sbin
Log:    /snap/freecad/754/usr/bin
Log:    /snap/freecad/754/sbin
Log:    /snap/freecad/754/bin
Log:    /usr/local/sbin
Log:    /usr/local/bin
Log:    /usr/sbin
Log:    /usr/bin
Log:    /sbin
Log:    /bin
Log:    /usr/games
Log:    /usr/local/games
Log:    /snap/freecad/754/kf5/usr/bin
Log: Init: App::FreeCADInit.py done
Log: Init: Creating Gui::Application and QApplication
Wrn: Qt: Session management error: Could not open network socket
Log: OpenGL version is: 4.6 (4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1)
Log: Run Gui init script
Log: Init: Running FreeCADGuiInit.py start script...
Log: Init:   Searching modules...
Log: Init:      Initializing /snap/freecad/754/usr/Mod/AddonManager... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Arch... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Draft... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Fem... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Idf(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Import... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Inspection... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Material... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Measure(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Mesh... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/MeshPart... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/OpenSCAD... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Part... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/PartDesign... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Path... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Plot(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Points... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/ReverseEngineering... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Robot... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Show(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Sketcher... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/SnapSetup(InitGui.py not found)... ignore
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Spreadsheet... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Start... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Surface... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/TechDraw... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Test... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Tux... done
Log: Init:      Initializing /snap/freecad/754/usr/Mod/Web... done
Log: Init:      Initializing /home/madhead/snap/freecad/common/Mod/btl/./... failed
Log: ----------------------------------------------------------------------------------------------------
Log: Traceback (most recent call last):
  File "<string>", line 136, in RunInitGuiPy
  File "<string>", line 1, in <module>
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/home/madhead/snap/freecad/common/Mod/btl/./btl/__init__.py", line 4, in <module>
    from .tool import Tool
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/home/madhead/snap/freecad/common/Mod/btl/./btl/tool.py", line 5, in <module>
    from .feeds.util import cantilever_deflect_endload, cantilever_deflect_uniload
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/home/madhead/snap/freecad/common/Mod/btl/./btl/feeds/__init__.py", line 1, in <module>
    from .calc import FeedCalc
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/home/madhead/snap/freecad/common/Mod/btl/./btl/feeds/calc.py", line 3, in <module>
    from scipy.optimize import minimize
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/snap/freecad/754/usr/lib/python3/dist-packages/scipy/optimize/__init__.py", line 400, in <module>
    from ._minimize import *
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/snap/freecad/754/usr/lib/python3/dist-packages/scipy/optimize/_minimize.py", line 27, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/snap/freecad/754/usr/lib/python3/dist-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/snap/freecad/754/usr/lib/python3/dist-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 10, in <module>
    from .equality_constrained_sqp import equality_constrained_sqp
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/snap/freecad/754/usr/lib/python3/dist-packages/scipy/optimize/_trustregion_constr/equality_constrained_sqp.py", line 4, in <module>
    from .projections import projections
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/snap/freecad/754/usr/lib/python3/dist-packages/scipy/optimize/_trustregion_constr/projections.py", line 8, in <module>
    from sksparse.cholmod import cholesky_AAt
  File "/snap/freecad/754/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "sksparse/cholmod.pyx", line 1, in init sksparse.cholmod
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Log: ----------------------------------------------------------------------------------------------------
Err: During initialization the error "numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject" occurred in /home/madhead/snap/freecad/common/Mod/btl/./InitGui.py
Err: Please look into the log file for further information
Log: All modules with GUIs using InitGui.py are now initialized
Log: All modules with GUIs initialized using pkgutil are now initialized
Log: Init: Loading FreeCAD GUI
Log: Init: Running FreeCADGuiInit.py start script... done
Log: Init: Activating default workbench StartWorkbench
Log: Loading GUI of Web module... done
Log: Loading GUI of Start module... done
Log: Loading Start module... done
Log: Sandboxing disabled by user.
Log: Init: Showing main window
Log: Main window restored
Log: Show main window
Log: Toolbars restored
Log: Couldn't connect to spacenav daemon. Please ignore if you don't have a spacemouse.
Log: Init: Entering event loop
Log: Init: Executing event loop...
Log: Init: Processing command line files
```

**Comment by knipknap** [comment]
`02:53:54  During initialization the error "numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject" occurred in /home/siarhei_krukau/snap/freecad/common/Mod/btl/./InitGui.py
`

This is a bug in the Snap package, not by BTL. You can check for yourself: If you enter "from scipy import optimize" into the Python console in FreeCAD, you will get this error. You will have to contact the Snap author to fix the numpy or scipy version in the package.
